#!/usr/bin/env bash
# Setup wizard for private-quartz-publish server stack.
# Prompts for the two pieces of information that have to be local to your
# server (vault directory + publish domain), writes them to .env, then
# pulls the pre-built images and starts the services.

set -euo pipefail

cd "$(dirname "$0")"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
dim() { printf '\033[2m%s\033[0m\n' "$*"; }
fail() { printf '\033[1;31m%s\033[0m\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || fail "docker not found. Install Docker first."
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  fail "Neither 'docker compose' nor 'docker-compose' is available."
fi

bold "Private Quartz Publish — server setup"
echo
dim "This will:"
dim "  1. Ask for your vault directory path and your public domain"
dim "  2. Write them to .env"
dim "  3. Pull the pre-built docker images and start the stack"
dim "  4. Caddy will obtain a Let's Encrypt cert automatically"
echo

if [ -f .env ]; then
  echo ".env already exists."
  read -rp "Overwrite with a fresh one? [y/N] " resp
  case "$resp" in
    y|Y) ;;
    *) echo "Keeping existing .env."; skip_env=1 ;;
  esac
fi

if [ -z "${skip_env:-}" ]; then
  while :; do
    read -rp "Absolute path to your vault directory on this server: " vault_dir
    [ -d "$vault_dir" ] && break
    echo "  -> Directory does not exist. Try again."
  done

  while :; do
    read -rp "Public domain to serve published notes at (e.g. notes.example.com): " publish_domain
    [[ -n "$publish_domain" && "$publish_domain" != *" "* ]] && break
    echo "  -> Domain looks invalid. Try again."
  done

  cat > .env <<EOF
# Generated by setup.sh on $(date -u +%FT%TZ)
VAULT_DIR=$vault_dir
PUBLISH_DOMAIN=$publish_domain
EOF
  echo
  echo "Wrote .env:"
  sed 's/^/  /' .env
fi

mkdir -p publish/content publish/site

echo
bold "Pulling images..."
$COMPOSE pull

echo
bold "Starting services..."
$COMPOSE up -d

echo
bold "Done."
. ./.env
cat <<EOF

Next steps:
  1. Make sure DNS for $PUBLISH_DOMAIN points at this server.
  2. Install the Obsidian plugin (see project README) and set its
     "Base URL" setting to:  https://$PUBLISH_DOMAIN
  3. Right-click any note in Obsidian → "Publish to web".
  4. Visit https://$PUBLISH_DOMAIN/<slug-from-clipboard>

Logs:    $COMPOSE logs -f
Stop:    $COMPOSE down
Update:  $COMPOSE pull && $COMPOSE up -d
EOF
